//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Callboard.App.Web.CommercialService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commercial", Namespace="http://schemas.datacontract.org/2004/07/Callboard.Service.Commercial")]
    [System.SerializableAttribute()]
    public partial class Commercial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageExtensionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageExtension {
            get {
                return this.ImageExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageExtensionField, value) != true)) {
                    this.ImageExtensionField = value;
                    this.RaisePropertyChanged("ImageExtension");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommercialService.ICommercialRepository")]
    public interface ICommercialRepository {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommercialRepository/GetCommercials", ReplyAction="http://tempuri.org/ICommercialRepository/GetCommercialsResponse")]
        Callboard.App.Web.CommercialService.Commercial[] GetCommercials();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommercialRepository/GetCommercials", ReplyAction="http://tempuri.org/ICommercialRepository/GetCommercialsResponse")]
        System.Threading.Tasks.Task<Callboard.App.Web.CommercialService.Commercial[]> GetCommercialsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommercialRepositoryChannel : Callboard.App.Web.CommercialService.ICommercialRepository, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommercialRepositoryClient : System.ServiceModel.ClientBase<Callboard.App.Web.CommercialService.ICommercialRepository>, Callboard.App.Web.CommercialService.ICommercialRepository {
        
        public CommercialRepositoryClient() {
        }
        
        public CommercialRepositoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommercialRepositoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommercialRepositoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommercialRepositoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Callboard.App.Web.CommercialService.Commercial[] GetCommercials() {
            return base.Channel.GetCommercials();
        }
        
        public System.Threading.Tasks.Task<Callboard.App.Web.CommercialService.Commercial[]> GetCommercialsAsync() {
            return base.Channel.GetCommercialsAsync();
        }
    }
}
