USE [callboardDB];
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(1, 2)
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(1, 3)
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(2, 3)
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(3, 1)
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(4, 5)
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(5, 6)
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(6, 7)
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(7, 0)
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(8, 4)
INSERT INTO [dbo].[AdsInCategories]([AdId], [CategoryId]) VALUES(8, 7)