USE [callboardDB];
--Brest region
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(1, "Byelaazyorsk")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(1, "Brest")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(1, "Baranavichy")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(1, "Davyd-Haradok")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(1, "Drahichyn")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(1, "Kamyanyets")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(1, "Kobryn")
--Gomel region
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(2, "Brahin")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(2, "Khoiniki")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(2, "Chachersk")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(2, "Dobrush")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(2, "Gomel")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(2, "Kalinkavichy")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(2, "Mazyr")
--Grodno region
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(3, "Grodno")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(3, "Astravyets")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(3, "Ashmyany")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(3, "Dzyatlava")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(3, "Iwye")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(3, "Masty")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(3, "Navahrudak")
--Minsk region
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(4, "Barysaw")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(4, "Chervyen")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(4, "Fanipal")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(4, "Krupki")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(4, "Lahoysk")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(4, "Lyuban")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(4, "Kletsk")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(4, "Minsk")
--Mogilev region
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(5, "Mogilev")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(5, "Babruysk")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(5, "Bykhaw")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(5, "Kastsyukovichy")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(5, "Klimavichy")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(5, "Krychaw")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(5, "Mstsislaw")
--Vitebsk region
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(6, "Vitebsk")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(6, "Dokshytsy")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(6, "Dzisna")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(6, "Dubrowna")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(6, "Hlybokaye")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(6, "Lepiel")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(6, "Myory")
--Moscow region
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(7, "Moscow")
--Smolensk region
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(8, "Smolensk")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(8, "Velizh")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(8, "Vyazma")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(8, "Yartsevo")
INSERT INTO [dbo].[City]([AreaId], [Name]) VALUES(8, "Yelnya")