USE [callboardDB];
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(1, 1)
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(2, 2)
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(3, 3)
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(4, 4)
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(5, 5)
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(6, 6)
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(7, 7)
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(8, 8)
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(9, 9)
INSERT INTO [dbo].[ImagesInAds]([ImageId], [AdId]) VALUES(10, 10)