USE MASTER;
GO

CREATE LOGIN max_bro 
    WITH PASSWORD = N'1D2F2f3E3asd', 
    DEFAULT_DATABASE = MASTER, 
    DEFAULT_LANGUAGE = US_ENGLISH;
GO

ALTER LOGIN max_bro ENABLE;
GO

ALTER SERVER ROLE  sysadmin  ADD MEMBER max_bro;  

GRANT CONTROL SERVER TO max_bro;