USE [callboardDB];
GO
CREATE LOGIN admin_max 
    WITH PASSWORD    = N'maxbro2968',
    CHECK_POLICY     = OFF,
    CHECK_EXPIRATION = OFF;
GO
CREATE USER maksim
GRANT EXECUTE, SELECT, INSERT, UPDATE, DELETE ON SCHEMA :: dbo
GO
